### ISSUE TITLE
Downstream tasks

### ISSUE THREAD

**Issue by kaushikCanada** [JoelStansbury/ipypdf#2]
First of all this is an awesome library.

I was looking to make a question answring bot on the graph made from the cytoscape, NER, and all the stuff. how do i do that? do i extract the graph and save somewhere or somethig? can you give some suggestions?

**Comment by JoelStansbury** [comment]
Hi Kaushik,
There is no way to export the graph yet. I can see about adding something in on Friday.
The NER tables are literally just `nlp(doc).ents` at the moment (see https://spacy.io/usage/linguistic-features#named-entities-101).

As for suggestions, you might want to read through the tests. There is a different framework used to simulate actual button clicks rather than simply exposing the utils like the APIExample notebook shows. The code also looks much nicer.

**Comment by kaushikCanada** [comment]
Hi JoelStansbury,

Thank you so much for your reply. This is really exciting. I am trying to
create a knowledge graph and run qna on it. looking forward to more in this
package.

Thanks,
Kaushik

**Comment by kaushikCanada** [comment]
I am having an issue with the left tree pane. the bottom scrolling from
left to right is not working.

**Comment by JoelStansbury** [comment]
@kaushikCanada 
I just merged in the change for exporting the edgelist. It'll probably go up to PyPi in the next week or so.
Here's a template for computing and returning the edgelist programatically
```python
from ipypdf import App
from ipypdf.widgets.node_tools import Cytoscape

app = App(f"../pdfs", bulk_render=False)
tool = Cytoscape(app.root)
tool.refresh()
edgelist = tool.edges
```

And yes, the scrolling isn't the best is it. I think there was a good reason for that. There is a layout tool from wxyz that I've been wanting to use here, just haven't gotten around to it

**Comment by JoelStansbury** [comment]
Well, I re-enabled scrolling and nothing is visibly broken. I think I originally just wanted to get the scrollbar on the left-hand side and never did it

**Comment by kaushikCanada** [comment]
Thank you so much Joel. Now i am going to dive into this :) . Lets see if i
can create the graph for some chapters of a geography book

**Comment by JoelStansbury** [comment]
Awesome! Good luck

**Comment by JoelStansbury** [comment]
If you find that the tool becomes unusably slow after parsing, you might want to try pulling the latest `main` code.
I had to refactor the tree widget to fix the issue.
You should be able to import old files, but I've added the `0.0.9` branch in case you need to stick with that code-base.
Both are up on pypi as well.

**Comment by kaushikCanada** [comment]
Aha! Thank you for this info so I will pull from main. Will be testing this
during the weekend.

Thanks,
Roy
